semaphoreci/toolbox

cache

Reverts semaphoreci/toolbox#29

Revert "Formatting the list output log"

---

cache

Improvement for the cache list output log

---

.semaphore/semaphore.yml
sem-version

Added c and cpp support to sem-version

---

sem-service

Measures how long it takes to start a container using sec-service and stream the result in to a file - stats.txt

Docker start duration stats

---

libcheckout
tests/checkout_tests

Reverts semaphoreci/toolbox#55

Revert "Change clone depth"

---

tests/cache.bats

Adding tests for cache store and restore in order to verify that these functions don't change current dir.

Cache: Add test for unwanted changes in current dir

---

.semaphore/semaphore.yml
install-toolbox
libcheckout
tests/libcheckout.bats

Toolbox support for Darwin.

---

libchecksum

Add MacOS support for libchecksum

add support for macos

---

sem-install

Needed to remove "" from the php.ini file

Php.ini not found

---

sem-version

A small addition to sem-version to install elixir version before trying to switch to it

Install elixir if not installed

---

sem-install

Update var naming in sem-install

change var name

---

.semaphore/semaphore.yml
install-toolbox

Fix for https://github.com/semaphoreci/toolbox/issues/88
In addition, included tests for MacOS platform.

Issue 88: Toolbox installation requires sudo which might not be installed in Docker containers

---

libcheckout
tests/libcheckout.bats

Introducing `git checkout -qf` we brake builds some of our customers
https://github.com/semaphoreci/toolbox/pull/94#pullrequestreview-258407005

Use git reset to set the sha

---

.semaphore/semaphore.yml
cache
tests/macOS_autocache.bats
tests/macOS_cache.bats

Fix restored path for macos cache and cache bats for macOS agent

fix restored path for macos cache

---

cache

Update cache to support parallel uploads and prevent archive corruption.

Update cache to support parallel uploads

---

install-toolbox
toolbox

Reverts semaphoreci/toolbox#113

Revert "rectify install path for toolbox install"

---

.semaphore/semaphore.yml
install-toolbox
sem-service
sem-service-check-params
tests/cache.bats
tests/macOS_cache.bats

Ability to add username and password to mysql, postgres, mongodb.
Also provide default socket for mysql and postgres on the host.

Parametrized sem-service

---

.semaphore/semaphore.yml
sem-install
sem-version

Nvm use our mirror to download nodejs

---

libcheckout

Checkout will not exit session on error and return accurate status codes.

Exit -> Return

---

.semaphore/semaphore.yml
sem-install

New ruby installs did not contain bundler.

sem-install install bundler with ruby

---

sem-install

So it actually gets the paramethers. !

Add $@ to the end of composer

---

.semaphore/semaphore.yml

Consistency and quality checks for Bash utilities.

Shellcheck

---

.semaphore/semaphore.yml
sem-version

sem-version ruby 'ruby-version' -f will override any .ruby-version files present

Sem version force ruby version flag

---

.semaphore/semaphore.yml
sem-service

Please share your thoughts about the approach.

Nb sem-service registry

---

sem-service

Not sure if it affects anything, though.

Fix a typo in sem-service

---

release/create.sh
tests/sftp_server/start_on_linux.sh

related to https://github.com/semaphoreci/semaphore/issues/63

Update SPC and fix empty change in bug

---

sem-install
tests/sem_version_bionic.bats

Removed npm upgrade since it causes issues with older versions of nodejs

removed npm upgrade

---

tests/sem_version_container.bats

Flutter tests started failing: https://semaphore.semaphoreci.com/jobs/c97ad916-48c1-4415-91c0-4ceb9a4e3674#L249. Probably related to https://github.com/renderedtext/dockerfile-renderer/commit/cf857806164595135934c0b81c4479a716bb127e.

Update flutter version in tests

---

cache-cli/pkg/storage/sftp_store.go
cache-cli/pkg/storage/storage_test.go
cache-cli/pkg/storage/store_test.go

Use a temporary file when storing, to avoid concurrent writes issues. This is something we did in the old cache CLI, but wasn't replicated in the new one.
Note: since the added test for concurrency writes require creating and uploading big files, the time it takes for the test to run increased around ~30s:
```
Before:
PASS pkg/storage.Test__Store (2.11s)
After:
PASS pkg/storage.Test__Store (33.61s)
```
However, I think this is a good test, so I think having extra 30s of testing is not a big deal here.

New cache CLI: use temporary file when storing

---

system-metrics-collector

Reverts semaphoreci/toolbox#312

Revert "Added system metrics for shm"

---

release/create.sh
tests/artifacts.bats

This reverts commit b9c8b7e3597b4faf57eb46e8d32d210ab2228d54.

revert: include artifact CLI for Windows (#327)

---

cache-cli/pkg/files/lookup.go
cache-cli/pkg/files/lookup_test.go

Related to https://github.com/renderedtext/tasks/issues/3019.

Use main branch as fallback for restore

---

release/create.sh

https://github.com/semaphoreci/spc/pull/40

Use new SPC with a bugfix for non-master PRs

---

.semaphore/semaphore.yml
tests/sem_version_bionic/elixir.bats
tests/sem_version_bionic/erlang.bats
tests/sem_version_bionic/firefox.bats
tests/sem_version_bionic/gcc.bats
tests/sem_version_bionic/go.bats
tests/sem_version_bionic/java.bats
tests/sem_version_bionic/kubectl.bats
tests/sem_version_bionic/node.bats
tests/sem_version_bionic/php.bats
tests/sem_version_bionic/python.bats
tests/sem_version_bionic/ruby.bats
tests/sem_version_bionic/scala.bats

Also, disables the firefox test due to a mismatch on versions available.

fix: update sem-version tests

---

.semaphore/semaphore.yml
sem-install
sem-version
tests/sem_version_bionic/elixir.bats
tests/sem_version_bionic/erlang.bats
tests/sem_version_bionic/firefox.bats
tests/sem_version_bionic/php.bats
tests/sem_version_focal/php.bats

- Added support for Elixir 1.14.x
- Removed hard-coded Firefox versions
- Test bumps

Alias version bump

---

release/create.sh
tests/sem_version_container.bats

- Updates test-results CLI to 0.6.3
- Fixes sem-version tests for Flutter

feat: include test-results CLI in self-hosted Windows toolbox

---

cache-cli/pkg/archive/native_archiver.go

This makes the decompressor's behavior a little closer to how the tar CLI behaves.

fix: return error only when all tar blocks have been processed

---

.semaphore/semaphore.yml
libcheckout
retry

- in case checkout fails to clone prints out error message 
- checkout can be called with `retry checkout`

Print stderr in case clone fails and add toolbox functions to retry ommands

---

.semaphore/semaphore.yml

Add missing deps in the after-pipeline jobs.

Download missing deps for after ppl

---

sem-service
sem-service-check-params
tests/sem_service/elasticsearch

Changed the way how elasticsearch is started, to be able to pass commands to the docker container through `sem-service`.

Parameters for ES

---

release/create.sh

https://github.com/renderedtext/tasks/issues/6860
https://github.com/semaphoreci/spc/releases/tag/v1.12.0

Update spc CLI to v1.12.0

---

.semaphore/semaphore.yml

https://github.com/renderedtext/tasks/issues/6969

fix(ci) adds mirrors for trivy db repositories

---

cache-cli/Makefile
release/create.sh
sem-context/Makefile

https://github.com/renderedtext/tasks/issues/6860
https://github.com/semaphoreci/spc/releases/tag/v1.12.1

Update SPC to version v1.12.1

---

sem-dockerize

https://github.com/renderedtext/tasks/issues/6451

Update timeout for sem-dockerize

---

cache-cli/go.mod
cache-cli/go.sum

https://github.com/renderedtext/tasks/issues/7286

build(cache-cli): update golang.org/x/net to v0.33.0

---

sem-install
sem-version
tests/sem_version_focal/elixir.bats
tests/sem_version_focal/erlang.bats
tests/sem_version_focal/ruby.bats
tests/sem_version_jammy/elixir.bats
tests/sem_version_jammy/erlang.bats
tests/sem_version_jammy/ruby.bats
tests/sem_version_noble/elixir.bats
tests/sem_version_noble/erlang.bats
tests/sem_version_noble/ruby.bats

- Alias and tests bump
- Added support for Elixir 1.18.x

Elixir 1.18.x

---

sem-install

https://github.com/renderedtext/tasks/issues/7515

Update rbenv for Ruby build

---

.semaphore/semaphore.yml
sem-service
sem-service-check-params
tests/sem_service/redis
tests/sem_service/valkey

- feat: add support to sem-service for Redis 8 and Valkey 8

feat: add support to sem-service for Redis 8 and Valkey 8

---

release/create.sh
tests/artifacts.bats

New artifact CLI: https://github.com/semaphoreci/artifact/releases/tag/v0.6.7

build: update artifact CLI version to v0.6.7

---

.semaphore/semaphore.yml
test-results/Makefile

Add test-results CLI linting reports

Add linter to test results CLI

---

sem-version
tests/sem_version_focal/erlang.bats
tests/sem_version_focal/ruby.bats
tests/sem_version_jammy/elixir.bats
tests/sem_version_jammy/erlang.bats
tests/sem_version_jammy/gcc.bats
tests/sem_version_jammy/go.bats
tests/sem_version_jammy/java.bats
tests/sem_version_jammy/kubectl.bats
tests/sem_version_jammy/node.bats
tests/sem_version_jammy/php.bats
tests/sem_version_jammy/python.bats
tests/sem_version_jammy/ruby.bats
tests/sem_version_jammy/scala.bats
tests/sem_version_noble/elixir.bats
tests/sem_version_noble/erlang.bats
tests/sem_version_noble/gcc.bats
tests/sem_version_noble/go.bats
tests/sem_version_noble/java.bats
tests/sem_version_noble/kubectl.bats
tests/sem_version_noble/node.bats
tests/sem_version_noble/php.bats
tests/sem_version_noble/python.bats
tests/sem_version_noble/ruby.bats
tests/sem_version_noble/scala.bats

- Update `sem-version` aliases:
- Ruby 3.1 -> 3.1.7
- Ruby 3.2 -> 3.2.9
- Ruby 3.3 -> 3.3.9
- Ruby 3.4 -> 3.4.6
- Erlang 28 -> 28.1

feat: update sem-version aliases
