sem-service
When calling `start`, forward the rest of the arguments to `docker run`
=> Forward all command line arguments to docker run

libcheckout
Previously the checkout have generated the following example output:
```
Cloning into 'guard'...
remote: Counting objects: 963, done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 963 (delta 87), reused 140 (delta 48), pack-reused 747
Receiving objects: 100% (963/963), 149.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (480/480), done.
Checking connectivity... done.
```
Without showing the branch nor version of the code being set.
By using these commands the output would be the following:
```
Cloning into 'guard'...
remote: Counting objects: 963, done.
remote: Compressing objects: 100% (156/156), done.
remote: Total 963 (delta 87), reused 140 (delta 48), pack-reused 747
Receiving objects: 100% (963/963), 149.42 KiB | 0 bytes/s, done.
Resolving deltas: 100% (480/480), …
```
=> Checkout: Show branch and commit in the output

cache
This PR is opened to avoid confusion caused by differences in evaluating $HOME variable in Docker based jobs. Job is able to communicate with cache server, key is present in in job environment, but warning log is printed.
=> Skip SSH key check

.semaphore/semaphore.yml, cache, tests/autocache.bats, tests/cache.bats
Improve current caching mechanism - detecting project structure and storing dependencies into cache when `cache store` or `cache restore` is called without any additional arguments
example usage: 
based on https://docs.semaphoreci.com/article/99-rails-continuous-integration
```
blocks:
- name: Setup
task:
jobs:
- name: bundle
commands:
- checkout
- cache restore
- sem-version ruby 2.6.0
- bundle install --deployment -j 4 --path vendor/bundle
- cache store
```
=> Caching that recognizes the project structure

cache, tests/cache.bats
Store/Resotre behaviour should not change for relative paths:
`cache store abc dir1/`
`cache store xyz ../../dir1/`
`cache restore abc`
`cache restore xzy`
Restore to the current directory, wherever is the PWD for user
Store/Restore behaviour if the path contains the leading `/`:
- Absolute paths:
`cache store abc /var/dir1`
`cache store xyz /var/foo/file.txt`
`cache restore abc`
`cache restore xyz`
Will result in cache archive being restored to /var/dir1 and /var/foo/file.txt
=> cache absolute paths

cache
Fix issue with the macOS cache command failing when removing old keys.
=> Fix cache command for macOS

.semaphore/semaphore.yml, install-toolbox, toolbox
Updated the `install-toolbox` script to install toolbox utils inside local user dir without sudo if running inside container as unprivileged user. if running inside the container as `root` or as a semaphore user on a regular VM, toolbox installation behaviour is unchanged.
To help determine if we are running inside a container or a VM, a new environment variable was introduced: `SEMAPHORE_AGENT_MACHINE_ENVIRONMENT_TYPE` which can have a value of:
`container` or `VM`.
docs ref: https://docs.semaphoreci.com/article/12-environment-variables#semaphore_agent_machine_environment_type
=> update install-toolbox to install without sudo

.semaphore/semaphore.yml, install-toolbox, toolbox
Reverts semaphoreci/toolbox#110
Reverting this PR. We got one report that the cache CLI is not installed in a container. I'm not yet 100% sure that this is the cause, but the safest option for now, is to revert.
=> Revert "update install-toolbox to install without sudo"

install-toolbox, toolbox
INSTALL_PATH is now reset after the platform check is finished, creating
the missing folder with it if need be. This also keeps the INSTALL_PATH changes isolated to the top section, leaving the `install_cmd` to smaller set of things to do.
the command was not run for the container environment thus ... not adding links to the tools anymore so this introduces it back
finally, to avoid adding multiple times the install path in the PATH a
quick grep check on the profile will limit runs to only once
=> rectify install path for toolbox install

cache
Currently nvm can be used in Semaphore2, but the default cache does not make use of it. Many node projects need to add support for nvm manually, as they want their tests to run on a specific version of nodejs.
This PR adds support for detecting and caching nvm files.
=> add caching support for nvm

cache
This allows the cache restore command to be used multiple times at the same time.  ie:
```
cache restore bundle-cache-master &
cache restore yarn-cache-master &
```
We have found that this allows our Semaphore build to improve by 1-2 minutes, helping us to get to a 10min build.
=> Multiple cache restore support 

install-toolbox, system-metrics-collector
A very thin agent for collecting system metrics. This agent should be able to work in any Docker image, Linux VM or on Mac OS.
Metrics are collected in `/tmp/system-metrics`. These metrics can be used in two ways:
- In the userspace by adding `cat /tmp/system-metrics` as an epilogue command.
- In the inspection state, extracted from running VMs.
The metrics can offer valuable basic insights into the state of the Jobs and potentialy uncover problems.
---
Futher advancements in this area could be to change to format to JSON, collect and display these metrics in the UI.
=> Simple System Metrics Collector

cache
In an attempt to speed up the builds, we run a number of commands concurrently.  This causes issues with some cache commands, as shown below.
In this code, we call `cache store..` 3 times and if the cache is full we can hit issues as the filename is shared by all the processes and one of them can delete the file causing the others to error.  Following PR adds a process id to all temp filenames that appear relevant.
I haven't tested yet, but can generate a patch and apply on the fly if you feel this is needed.
```
Not enough space, deleting the oldest keys.
Key yarn-master-d379f217bbd4cfc991a37e185150bb47 is deleted.
Uploading '/home/semaphore/chopin/public/' with cache key 'public-master-4391c85f-9024-490c-bb9d-55a439aea4f1'...
Key node-modules-master-d379f217bbd4cfc991a37e185150bb47 is …
```
=> Use process specific temp files to fix concurrency issues

.semaphore/semaphore.yml
Lowering the warning limits for shellcheck. New values are set based on values in master CI build.
=> Adjust shellcheck limits

.semaphore/semaphore.yml, install-toolbox, release/create.sh
The newly introduced compile stage (example: https://semaphore.semaphoreci.com/workflows/af0e81c1-84a6-4e81-a5bf-acc3bb1603a2) needs these two CLIs in the Toolbox to work efficiently.
We are adding:
- Semaphore Pipeline Compiler (SPC): Compiles change_in expressions in Pipelines
- When: Evaluates "when" expressions in pipelines
=> Add Semaphore Pipeline Compiler to the Toolbox

install-toolbox, system-metrics-collector
1. Update system metrics collector to be location based, not depending on drive naming. 
2. Added docker space metrics. 
3. Changed install path to work with ubuntu 20.04
=> Multiple minur updates

sem-version, tests/sem_version_bionic.bats
sem-version alias change for Ruby and PHP and tests update
Ruby: 2.6.8, 2.7.4, 3.0.2
PHP: 7.3.29, 7.4.21, 8.0.8
=> php,ruby bump

cache-cli/pkg/storage/sftp_store.go
Using the cache key entry as part of the temporary file name used during upload makes the temporary file visible to cache restores using the same key. That leads to incomplete files being restored.
This PR removes the cache key from the temporary file name to avoid such issues.
=> fix: remove cache key from temporary file name

release/create.sh, tests/sem_version_container.bats
Reverts semaphoreci/toolbox#338
Customers reported errors with monorepo support for PRs to non-master branches.
=> Revert "Release spc v1.9.3"

release/create.sh
During one of the artifact CLI version rollbacks, we removed it from the self-hosted Windows toolbox. See: https://github.com/semaphoreci/toolbox/pull/331.
Since then, we have updated the artifact CLI version again but forgot to re-include the artifact CLI in the self-hosted Windows toolbox.
=> fix: re-add artifact CLI in windows self-hosted toolbox

.semaphore/semaphore.yml, cache-cli/Makefile, release/create.sh, release/upload.sh
- Updates cache-cli to build for `amd64` and `arm64`.
- Updates `release/create.sh` script to create tarballs for amd64 and arm64, for Linux and Darwin.
- Updates `release/upload.sh` to upload the new ARM tarballs.
=> feat: create self-hosted ARM toolbox

.semaphore/release.yml
https://github.com/semaphoreci/toolbox/pull/367 changed the artifact names for the cache CLI. This pulls them from the right place.
=> fix: release promotion

cache-cli/pkg/storage/s3.go
If one intends to force the cache CLI to use the EC2 instance profile (and not any other environment variables or files), there's no need to rely on an AWS CLI profile to be already configured in one of the configuration files. We can accomplish that by using the [ec2rolecreds](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/ec2rolecreds#hdr-Loading_credentials_with_the_Provider_directly) credentials provider. We put that behavior behind a `SEMAPHORE_CACHE_USE_EC2_INSTANCE_PROFILE` environment variable.
=> feat: add SEMAPHORE_CACHE_USE_EC2_INSTANCE_PROFILE

cache-cli/pkg/archive/native_archiver.go
When opening read-only files that already exist, `os.OpenFile()` complains because a read-only file can't be truncated. We handle that by attempting to remove the existing file and re-opening it when restoring it from the cache.
=> fix: handle existing read-only file on native archiver restore

cache-cli/pkg/archive/archiver_test.go, cache-cli/pkg/archive/native_archiver.go
A directory can be read-only and still have files inside of it. In that case, if we use the directory's permissions when creating it, we won't be able to write the files inside it. Instead, we should create the directory with writable permissions, write all the files inside it, and then apply the final permissions.
=> cache-cli: handle read-only directories

cache-cli/pkg/archive/archiver_test.go, cache-cli/pkg/archive/native_archiver.go, cache-cli/pkg/archive/shell_out_archiver.go
Sometimes the file is inside a directory, which is not in the archive. We handle that case by handling the `os.ErrNotExist` error when opening the file. If that happens, we create the parent directories, and try to open the file again.
=> fix: create parent directory if not in archive

libcheckout, tests/libcheckout.bats
This fixes the following scenario:
1. there is a branch `a` and commit `sha-1`
2. create branch `b` from the top of branch `a` so it contains commit `sha-1`
3. workflow is started for branch `b`
4. branch `b` is deleted
5. `checkout` command within the workflow is run in a shallow mode and the branch checkout fails since the branch `b` is not found
6. as a failover, checkout uses a full clone of the repo which sets up `master/main` as a working branch
7. checkout tries to switch to the targeted commit `sha-1` with `git reset --hard`
8. since that commit is present on branch `a` this will succeed but **the active branch will remain`master/main`**
As a fix, I introduced an additional step between 6) and 7) that tries to checkout the actual branch (branch `b` in the example) and fails if the …
=> libcheckout: Fail if branch is missing but sha exist on a different branch

.semaphore/semaphore.yml, libcheckout, sem-service, sem-version
We run [shellcheck](https://github.com/koalaman/shellcheck) during our CI, but we don't do anything about it. We should. This pull request addressed all the warnings for `checkout`, `sem-service` and `sem-version`. The main complaints were:
- https://www.shellcheck.net/wiki/SC2068
- https://www.shellcheck.net/wiki/SC2086
- https://www.shellcheck.net/wiki/SC2236
- https://www.shellcheck.net/wiki/SC2181
- https://www.shellcheck.net/wiki/SC2164
- https://www.shellcheck.net/wiki/SC2124
- https://www.shellcheck.net/wiki/SC2128
- https://www.shellcheck.net/wiki/SC2145
- https://www.shellcheck.net/wiki/SC2034
=> fix: address shellcheck warnings

libcheckout
Related to https://github.com/renderedtext/tasks/issues/5822. We are not properly using `SEMAPHORE_GIT_DEPTH` when fetching gIt objects/refs on pull request builds, which can make some pull request builds slow.
=> fix: use --depth on git fetch for PRs

sem-context/pkg/store/artifacts_store.go
In most cases it means file does not exist -> it means that key was not deleted and we can ignore that error.
task: https://github.com/renderedtext/tasks/issues/7117
=> Supress printing error if failing to generate signed URLs 

install-self-hosted-toolbox, install-toolbox, release/create.sh
This PR depends on https://github.com/renderedtext/when/pull/33 and the release of the new when CLI version v1.2.0.
We recently introduced the option for customers to choose an agent to run init jobs. 
If they choose the agent with the ubuntu2204 image they will have an issue with the `change_in` functionality.
For `change_in` to work we need the when CLI tool which in turn requires Erlang 24 to be installed on the machine and the ubuntu2204 images come with Erlang 25 as the default.
This PR changes the way when CLI is packaged and installed. 
It adds into the toolbox tarball all the different when CLI binaries for each supported Erlang version. 
Later in the installation phase, it installs the correct one based on the available Erlang version on the machine.
=> Change the when CLI installation procedure

sem-version, tests/sem_version_focal/elixir.bats, tests/sem_version_focal/erlang.bats, tests/sem_version_focal/ruby.bats, tests/sem_version_jammy/elixir.bats, tests/sem_version_jammy/erlang.bats, tests/sem_version_jammy/ruby.bats, tests/sem_version_noble/elixir.bats, tests/sem_version_noble/erlang.bats, tests/sem_version_noble/ruby.bats
- Add alias for Erlang 28.0
- Alias version bump
- Erlang 27: `27.2` -> `27.3`
- Elixir 1.18: `1.18.0` -> `1.18.4`
- Ruby 3.2: `3.2.6` -> `3.2.8`
- Ruby 3.3: `3.3.6` -> `3.3.8`
- Ruby 3.4: `3.4.1` -> `3.4.4`
=> feat: Add alias for Erlang 28.0, Alias version bump

.semaphore/semaphore.yml
The when CLI supports Erlang versions 24 -26, and the default Erlang version on the ubuntu2404 image is 27.
This is a known limitation that will be fixed in future versions of the when CLI and the toolbox.
Due to this the compiler test will fail on ubuntu2404, so this PR is removing them.
=> fix(ci pipeline): Removing tests since when CLI is not supported for ubuntu2404

.semaphore/semaphore.yml, system-metrics-collector
The system-metrics-collector script was based on Linux, with Linux-specific commands.
This PR makes it run and report on macOS-based systems.
=> feat: Adapt system-metrics-collector to work on macOS

cache-cli/go.mod, cache-cli/go.sum, test-results/cmd/command-metrics.go
1) Update cache-cli deps because of CVE-2025-22868
2) Update default src arg for test-results command-metrics to take into account default tmp dir for current os
Tested new changes on both macOS machines, and linux f1, all seems to work as expected, reports are being generated https://rtx.semaphoreci.com/workflows/38a7af1f-16ea-4528-a193-5510e47936e6?pipeline_id=ae52cbaa-9764-4215-9f80-3b899eac4793
https://github.com/renderedtext/tasks/issues/8193
=> Use os default tmp dir as default src arg

.semaphore/semaphore.yml, release/create.sh
When [CLI v1.3.0](https://github.com/renderedtext/when/releases/tag/v1.3.0) was released and now it support OTP 27.
Also enables compiler tests on Ubuntu 24.04.
Related [task](https://github.com/renderedtext/tasks/issues/6609) and also [this one](https://github.com/renderedtext/tasks/issues/8303).
=> build: update when CLI to v1.3.0 - with support for OTP 27

test-results/cmd/gen-pipeline-report.go, test-results/cmd/publish.go, test-results/cmd/root.go, test-results/pkg/cli/cli.go, test-results/pkg/cli/cli_stats_test.go, tests/test-results.bats
We introduced a file operation summary for push/pull commands in the artifact CLI. However, the test results CLI hides the output of the artifact CLI operations. To fix this, test-results will read output of the artifact operations and create a summary in the following form:
```
* [test-results] Artifact transfers:
*   → Pulled: 1 operation, 43 files, 62.8 KB
*   ← Pushed: 2 operations, 2 files, 24.1 KB
*   = Total: 3 operations, 45 files, 86.9 KB
```
=> Add artifact CLI summary to test result operations
